# Default values for the reserved-lane-simulation chart.

replicaCount: 1

host: "dt4mob.av.it.pt"

image:
  repository: "atnog-harbor.av.it.pt/dt4mob/reserved_lane_simulator"
  tag: "latest"
  imagePullPolicy: "Always"

service:
  port: 443
  targetPort: 8000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  host: "{{ .Values.host }}"
  path: /reserved-lane(/|$)(.*)
  tls:
    enabled: true
    secretName: "dt4mob-ingress-tls"

resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "2"
    memory: "2Gi"

config:
  logLevel: "DEBUG"

  auth:
    clientId: "ditto"
    audience: "account"
    serverUri: "https://{{ .Values.host }}/auth"
    internalServerUri: "http://dt4mob-keycloak:8080/auth/realms/dt4mob"
    issuer: 
      - "dt4mob-keycloak:8080/auth/realms/dt4mob"
      - "https://{{ .Values.host }}/auth/realms/dt4mob"
    signatureCacheTtl: 3600
    role: 
      - "admin"
    realm: "dt4mob"

  sumo:
    maxConcurrentJobs: 2
    jobTtlSeconds: 3600
    beginTime: 39346
    endTime: 40000
    stepLength: 0.1
