# Default values for the reserved-lane-simulation chart.

replicaCount: 1

image:
  repository: "atnog-harbor.av.it.pt/dt4mob/reserved_lane_simulator"
  tag: "latest"
  imagePullPolicy: "Always"

service:
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  host: "tomastest.com"
  path: /reserved-lane(/|$)(.*)

resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "2"
    memory: "2Gi"

config:
  logLevel: "DEBUG"

  auth:
    clientId: "ditto"
    audience: "account"
    serverUri: "https://tomastest.com/auth"
    internalServerUri: "http://dt4mob-keycloak:8080/auth/realms/dt4mob"
    issuer: 
      - "dt4mob-keycloak:8443/auth/realms/dt4mob"
      - "https://tomastest.com/auth/realms/dt4mob"
    signatureCacheTtl: 3600
    role: "historical-read"
    realm: "dt4mob"

  sumo:
    maxConcurrentJobs: 2
    jobTtlSeconds: 3600
    beginTime: 39346
    endTime: 40000
    stepLength: 0.1
