apiVersion: v1
kind: Service
metadata:
  name: {{ include "dt4mob-reserved-lane.fullname" . }}
  labels:
    {{- include "dt4mob-reserved-lane.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "dt4mob-reserved-lane.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
